### ISSUE TITLE
Create Cell struct inside grid.h

### ISSUE THREAD

**Issue by kapteenimuttipolpa** [kapteenimuttipolpa/game_of_life#2]
Struct should have a boolean value (or enum) that indicates cell's current state
It should also have some kind of a counter (like int) that can be used to keep track of how many alive cells are next to the cell --> FIX: let's not store the count

Struct should have a boolean value (or enum) that idicates the cell's next state (in the next evolution)

Initialize next_state to same than state;

Unit tests

**Comment by abhikumar63** [comment]
Hi,
I would like to contribute to this project. 
I have gone through the issue and I can solve it.

Basically we need to create struct which is user defined type containing three variables:

- bool currentState;
- int adjacentAliveCells;
- bool nextState;

If you have any other requirements please specify and do let me know about your response.

**Comment by kapteenimuttipolpa** [comment]
I am sorry abhikumar63 this is actually a school project so we cannot take you in 😢
